# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mashup09' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Reachability'
  # Pods for mashup09

end
